database:
  host: "localhost"
  port: 3306
  database: "herocrates"
  username: "root"
  password: ""
messages:
  only_players: "&cSolo i giocatori possono eseguire questo comando."
  no_permission: "&cNon hai il permesso per eseguire questo comando."
  player_not_found: "&cGiocatore non trovato, non è stato possibile dare la Cassa."
  invalid_crate_type: "&cTipo di Cassa non valido."
  invalid_key_type: "&cTipo di Chiave non valido."
  inventory_full_self: "&cIl tuo inventario è pieno."
  inventory_full_other: "&cL'inventario di {player} è pieno."
  received_crate: "&eHai ricevuto la cassa &b{crate}&e!"
  received_key: "&eHai ricevuto la chiave &b{key}&e!"
  given_crate: "&eHai dato una cassa di tipo &b{crate} &ea &b{player}&e!"
  given_key: "&eHai dato una chiave di tipo &b{key} &ea &b{player}&e!"
  invalid_amount: "&cPuoi dare un massimo di 64 di questo oggetto."
crates:
  normal:
    key:
        display_name: "Chiave normale"
        lore:
            - "Usa questa chiave per aprire la cassa!"
    display_name: "Cassa normale"
    item_name: "Cassa normale"
    item_lore:
      - "Piazza la cassa per renderla operativa!"
    hologram:
      - "&6Cassa Leggendaria"
      - "&7Clicca per aprire"
    rewards:
      - type: "ITEM"
        item: "DIAMOND_BLOCK"
        amount: 5
        probability: 50
      - type: "COMMAND"
        command: "give %player% diamond_sword"
        probability: 50
    guaranteed_rewards:
      30:
        - type: "ITEM"
          item: "DIAMOND_BLOCK"
          amount: 10
    animations:
      type: "SPIRAL"
      color: "RED"
      size: 2.0