database:
  host: ""
  port: 3306
  database: ""
  username: ""
  password: ""
messages:
  only_players: "&cSolo i giocatori possono eseguire questo comando."
  no_permission: "&cNon hai il permesso per eseguire questo comando."
  player_not_found: "&cGiocatore non trovato, non è stato possibile dare la Cassa."
  invalid_crate_type: "&cTipo di Cassa non valido."
  invalid_key_type: "&cTipo di Chiave non valido."
  inventory_full_self: "&cIl tuo inventario è pieno."
  inventory_full_other: "&cL'inventario di {player} è pieno."
  received_crate: "&eHai ricevuto la cassa &b{crate}&e!"
  received_key: "&eHai ricevuto la chiave &b{key}&e!"
  given_crate: "&eHai dato una cassa di tipo &b{crate} &ea &b{player}&e!"
  given_key: "&eHai dato una chiave di tipo &b{key} &ea &b{player}&e!"
  invalid_amount: "&cPuoi dare un massimo di 64 di questo oggetto."
  invalid_key: "&cNon hai la chiave giusta per aprire questa cassa."
  countdown_error: "&cDevi aspettare altri &b{time} &csecondi prima di aprire un'altra cassa."
  received_item: "&eHai ricevuto &bx{amount} {item}&e!"
crates:
  normal:
    countdown: 5
    key:
        display_name: "Chiave normale"
        lore:
            - "Usa questa chiave per aprire la cassa!"
    display_name: "Cassa normale"
    item_name: "Cassa normale"
    item_lore:
      - "Piazza la cassa per renderla operativa!"
    hologram:
      - "&6Cassa Leggendaria"
      - "&7Clicca per aprire"
    rewards:
      - type: "ITEM"
        item: "EMERALD_BLOCK"
        amount: 2
        probability: 10
        name: "&aBlocco di Smeraldo"
        lore:
          - "&7Un blocco di smeraldo"
      - type: "ITEM"
        item: "DIAMOND_BLOCK"
        amount: 5
        probability: 50
        name: "&bBlocco di Diamante"
        lore:
          - "&7Un blocco di diamante"
      - type: "ITEM"
        item: "IRON_BLOCK"
        amount: 10
        probability: 20
        name: "&fBlocco di Ferro"
        lore:
            - "&7Un blocco di ferro"
      - type: "ITEM"
        item: "NETHERITE_INGOT"
        amount: 1
        probability: 5
        name: "&5Lingotto di Netherite"
        lore:
            - "&7Un lingotto di netherite"
      - type: "ITEM"
        item: "DIAMOND_SWORD"
        amount: 1
        probability: 15
        name: "&bSpada di Diamante"
        lore:
            - "&7Una spada di diamante"
    gui_title: "&cCassa {crate}"
    guaranteed_rewards:
      30:
        - type: "ITEM"
          item: "DIAMOND_BLOCK"
          amount: 10
    # Animation type: SPIRAL, EXPLOSION
    animation:
      type: "SPIRAL"
      particle: "DRIPPING_HONEY"
      distance: 2
      sound:
        type: "ENTITY_PLAYER_LEVELUP"
        volume: 3.0
        pitch: 2.0