name: HeroCrates
version: '1.0-SNAPSHOT'
main: org.heroCrates.HeroCrates
api-version: '1.21'
author: 1100hero
commands:
  givecrate:
    description: 'Dai delle casse ad un giocatore'
    usage: '/givecrate <nome> <tipo> <quantità>'
    permission: herocrates.givecrate
  givekey:
    description: 'Dai delle chiavi ad un giocatore'
    usage: '/givekey <nome> <tipo> <quantità>'
    permission: herocrates.givekey
  givevirtualkey:
    description: 'Dai delle chiavi virtuali ad un giocatore'
    usage: '/givevirtualkey <nome> <tipo> <quantità>'
    permission: herocrates.givevirtualkey
softdepend: [PlaceholderAPI, SmartInvs]