name: HeroCrates
version: '1.0-SNAPSHOT'
main: org.heroCrates.HeroCrates
api-version: '1.21'
author: 1100hero
commands:
  givecrate:
    description: 'Dai una cassa ad un giocatore'
    usage: '/givecrate <nome> <tipo>'
    permission: herocrates.givecrate